#spring.application.name=my-vocabulary
spring:
  profiles:
    active:
      - dev
---
server:
  port: 1150
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    url: jdbc:postgresql://localhost:5432/my_eng
    username: postgres
    password: Tonpostgresql04
  jpa:
    properties:
      hibernate:
      format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
---
#spring:
#  config:
#    activate:
#      on-profile:
#        - test
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
